### ISSUE TITLE
开始抓包后进入口算pk就会提示断网

### ISSUE THREAD

**Issue by Harkerbest** [ph0ebus/XiaoYuanSolver#1]
开始抓包后进入口算pk就会提示断网，是不是证书要安装在系统目录

**Comment by ph0ebus** [comment]
参考一下相关安装CA证书的教程吧，估计是证书没装好然后HTTPS包传输出了问题？

https://mumu.163.com/help/20221018/35047_1047210.html

**Comment by Harkerbest** [comment]
嗯我看了是我手机上没有把证书装到系统证书上导致的，但是电脑模拟器刚配好口算pk就下架了，太难蚌了啊
